-record(sypex_meta, {
	vsn,
	creation_time,
	parser,
	encoding,
	elems_in_first_bytex_index,
	elems_in_main_index,
	blocks_in_single_elem,
	ranges,
	id_len,
	block_len,
	max_region_rec_size,
	max_city_rec_size,
	regions_size,
	cities_size,
	max_country_rec_size,
	countries_size,
	pack_format_descr_size,
	pack_format,
	first_byte_index,
	main_index,
	region_data,
	country_data,
	city_data

}).
